### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [amsantac/diffeR#2]
This package and **TOC** depend on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by amsantac** [comment]
Ok, I'll remove these dependencies for the diffeR and TOC packages. Thanks for the notice.

**Comment by amsantac** [comment]
The dependencies on those packages have been removed from diffeR and TOC (updated versions now on CRAN). Thanks.
